'\" t
.\"     Title: useradd
.\"    Author: Aurelien Requiem
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/18/2015
.\"    Manual: System Management Commands
.\"    Source: shadow-utils 4.2
.\"  Language: English
.\"
.TH "DNSCRYPT-WRAPPER" "8" "December 26th, 2016" "Debian GNU/Linux" "Admin Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -------